version: '3.8'

services:
  app:
    build:
      context: ..  # Contexto en la raíz del proyecto api-orders/
      dockerfile: docker/Dockerfile # Busca tu Dockerfile dentro de la carpeta docker/
    container_name: api_orders_app
    ports:
      - '8080:8080' # Puerto mapeado para que Jenkins o tu navegador accedan a la app
    environment:
      # ✅ CONFIGURACIÓN PARA H2: Apunta directamente a la memoria interna de la app
      SPRING_DATASOURCE_URL: jdbc:h2:mem:ordersdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.H2Dialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    restart: unless-stopped
    networks:
      - orders_net

networks:
  orders_net:
    name: api_orders_network # Nombre de la red interna en Docker